### ISSUE TITLE
kubeturbo pod is not registering with turbonomic server

### ISSUE THREAD

**Issue by tvishwanath-arkin** [turbonomic/kubeturbo#112]
The pod goes to running state for a while and terminates later

Pod Logs 
-----------

2017-10-06T11:53:43.885625883Z I1006 11:53:43.885269       1 mediation_container.go:52] ---------- Created MediationContainer ----------
2017-10-06T11:53:43.885693538Z I1006 11:53:43.885461       1 mediation_container.go:105] Registered CloudNative::Kubernetes
2017-10-06T11:53:43.885701828Z I1006 11:53:43.885471       1 kubeturbo_builder.go:154] No leader election
2017-10-06T11:53:43.885769522Z I1006 11:53:43.885550       1 mediation_container.go:67] Initializing mediation container .....
2017-10-06T11:53:43.885803094Z I1006 11:53:43.885669       1 client_websocket_transport.go:231] [performWebSocketConnection]: wss://10.XXX.XX.XXX:443/vmturbo/remoteMediation
2017-10-06T11:53:45.229815905Z E1006 11:53:45.229650       1 sdk_client_protocol.go:83] Protocol version negotiation failed%!(EXTRA string=REJECTED) :Protocol version "5.9.0-SNAPSHOT" is not allowed to communicate with server)
2017-10-06T11:53:45.229870068Z E1006 11:53:45.229683       1 sdk_client_protocol.go:27] Failure during Protocol Negotiation, Registration message will not be sent
2017-10-06T11:53:45.229877850Z E1006 11:53:45.229694       1 remote_mediation_client.go:134] Registration with server failed
2017-10-06T11:53:45.231859710Z panic: close of nil channel
2017-10-06T11:53:45.231885254Z 
2017-10-06T11:53:45.231891818Z goroutine 48 [running]:
2017-10-06T11:53:45.231897007Z panic(0x1651920, 0xc4201a20f0)
2017-10-06T11:53:45.233658579Z 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
2017-10-06T11:53:45.233675914Z github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer.(*remoteMediationClient).Stop(0xc4202e8410)
2017-10-06T11:53:45.233682841Z 	/Users/dongyiyang/Sandbox/Go/src/github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer/remote_mediation_client.go:163 +0x41
2017-10-06T11:53:45.233701311Z github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer.(*remoteMediationClient).Init(0xc4202e8410, 0xc420294e70)
2017-10-06T11:53:45.233707951Z 	/Users/dongyiyang/Sandbox/Go/src/github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer/remote_mediation_client.go:136 +0x710
2017-10-06T11:53:45.233713589Z github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer.InitMediationContainer(0xc420294e70)
2017-10-06T11:53:45.233718986Z 	/Users/dongyiyang/Sandbox/Go/src/github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer/mediation_container.go:77 +0x1f4
2017-10-06T11:53:45.233724973Z created by github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/service.(*TAPService).ConnectToTurbo
2017-10-06T11:53:45.233730298Z 	/Users/dongyiyang/Sandbox/Go/src/github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/service/tap_service.go:36 +0xdc

====================
Here's my config file
{
	"communicationConfig": {
		"serverMeta": {
                    "version": "6.0.0",
		    "turboServer": "https://10.XXX.XX.XXX:443"
		},
		"restAPIConfig": {
			"opsManagerUserName": "administrator",
			"opsManagerPassword": "password"
		}
	},
	"targetConfig": {
		"probeCategory":"CloudNative",
		"targetType":"Kubernetes",
		"address":"http://10.XXX.XX.XX:8080",
		"username":"",
		"password":""
	}
}

**Comment by tvishwanath-arkin** [comment]
Was using the wrong image. It works fine now

**Comment by enlinxu** [comment]
@tvishwanath-arkin Thanks for using Kubeturbo. May I ask how's your exp with Kubeturbo so far? Does it provide the value you were looking for?
